# Generated by Django 5.2.6 on 2025-11-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_enhance_models_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
