# Generated by Django 5.2.6 on 2025-11-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_invitation_barcode_image_invitation_barcode_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='dress_code',
            field=models.CharField(blank=True, help_text='e.g., Formal, Casual, Military Uniform', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='event_banner',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/'),
        ),
        migrations.AddField(
            model_name='event',
            name='menu',
            field=models.JSONField(blank=True, default=dict, help_text='Event menu details as JSON'),
        ),
        migrations.AddField(
            model_name='event',
            name='parking_info',
            field=models.TextField(blank=True, help_text='Parking instructions and availability'),
        ),
        migrations.AddField(
            model_name='event',
            name='program_schedule',
            field=models.JSONField(blank=True, default=dict, help_text='Event program/agenda as JSON'),
        ),
        migrations.AddField(
            model_name='event',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Any special instructions for guests'),
        ),
    ]
