# Generated by Django 5.2.6 on 2025-11-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_event_contact_email_event_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_assigned_seating',
            field=models.BooleanField(default=False, help_text='Whether this event has assigned seating'),
        ),
        migrations.AddField(
            model_name='event',
            name='seating_arrangement',
            field=models.JSONField(blank=True, default=dict, help_text='Seating arrangement details as JSON'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='seat_number',
            field=models.CharField(blank=True, help_text='Assigned seat number', max_length=50),
        ),
        migrations.AddField(
            model_name='invitation',
            name='table_number',
            field=models.CharField(blank=True, help_text='Assigned table number', max_length=50),
        ),
    ]
