"""Add CheckInSession model

Generated by assistant for audit sessions
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0011_alter_checkinlog_id_alter_seat_id_alter_table_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_checkin_sessions', to='auth.user')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_sessions', to='guests.event')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_checkin_sessions', to='auth.user')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
