# Generated by Django 5.2.6 on 2025-12-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0012_add_checkinsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplate',
            name='dress_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='has_assigned_seating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='menu',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='parking_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='program_schedule',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='photo',
            field=models.ImageField(blank=True, help_text='Guest profile photo', null=True, upload_to='guest_photos/'),
        ),
    ]
